const TENDERMINT_API_URL = process.env.REACT_APP_API_KEY;
const ASSETMANTLE_API_URL = process.env.REACT_APP_ASSET_MANTLE_API;
export const getBlockURL = (searchText) => `${TENDERMINT_API_URL}/block?height=${searchText}`;
// export const getStatusURL = () => `${TENDERMINT_API_URL}/status`;
export const getLatestBlockURL = () => `${TENDERMINT_API_URL}/block`;
export const getValidatorsURL = () => `${ASSETMANTLE_API_URL}/staking/validators`;
export const getBlocksURL = (min, max) => `${TENDERMINT_API_URL}/blockchain?minHeight=${min}&maxHeight=${max}`;
export const getBlockHeightURL = (height) => `${TENDERMINT_API_URL}/block_results?height=${height}`;
export const getTransactionURL = (txHash) => `${TENDERMINT_API_URL}/tx?hash=0x${txHash}&prove=true`;
export const getBlockByHashURL = (blockHash) => `${TENDERMINT_API_URL}/block_by_hash?hash=0x${blockHash}`;
export const getBlockTransactionsURL = (blockHeight) => `${TENDERMINT_API_URL}/tx_search?query=tx.height%3D${blockHeight}&prove=true&page=1&per_page=30&order_by=asc`;
export const addAccountURL = () => `${ASSETMANTLE_API_URL}/keys/add`;
export const recoverAccountURL = () => `${ASSETMANTLE_API_URL}/keys/recover`;